#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'ResourcesApi' {
    Context 'Get-VSiteDisclaimer' {
        It 'Test Get-VSiteDisclaimer' {
            #$TestResult = Get-VSiteDisclaimer -VsiteID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-VSiteLogo' {
        It 'Test Get-VSiteLogo' {
            #$TestResult = Get-VSiteLogo -VsiteID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
