#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SS6AdminApi' {
    Context 'Invoke-SS6AckAdminNotificationByID' {
        It 'Test Invoke-SS6AckAdminNotificationByID' {
            #$TestResult = Invoke-SS6AckAdminNotificationByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6AckAdminNotifications' {
        It 'Test Invoke-SS6AckAdminNotifications' {
            #$TestResult = Invoke-SS6AckAdminNotifications
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6BlockList' {
        It 'Test Add-SS6BlockList' {
            #$TestResult = Add-SS6BlockList -BlockListItem "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6CRTToCSR' {
        It 'Test Add-SS6CRTToCSR' {
            #$TestResult = Add-SS6CRTToCSR -Id "TEST_VALUE" -InlineObject7 "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6Cert' {
        It 'Test Add-SS6Cert' {
            #$TestResult = Add-SS6Cert -TLSCertificate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6LDAPConfig' {
        It 'Test Add-SS6LDAPConfig' {
            #$TestResult = Add-SS6LDAPConfig -LDAPConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6SSHHostKey' {
        It 'Test Add-SS6SSHHostKey' {
            #$TestResult = Add-SS6SSHHostKey -SSHHostKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6Script' {
        It 'Test Add-SS6Script' {
            #$TestResult = Add-SS6Script -Script "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6User' {
        It 'Test Add-SS6User' {
            #$TestResult = Add-SS6User -User "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6UserPublicKey' {
        It 'Test Add-SS6UserPublicKey' {
            #$TestResult = Add-SS6UserPublicKey -Id "TEST_VALUE" -SSHPubKey "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Add-SS6VFS' {
        It 'Test Add-SS6VFS' {
            #$TestResult = Add-SS6VFS -VirtualFileSystem "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6AdminLogin' {
        It 'Test Invoke-SS6AdminLogin' {
            #$TestResult = Invoke-SS6AdminLogin -VsiteID "TEST_VALUE" -XOTP "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6AdminLogout' {
        It 'Test Invoke-SS6AdminLogout' {
            #$TestResult = Invoke-SS6AdminLogout
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Clear-SS6BlockList' {
        It 'Test Clear-SS6BlockList' {
            #$TestResult = Clear-SS6BlockList
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Close-SS6SessionById' {
        It 'Test Close-SS6SessionById' {
            #$TestResult = Close-SS6SessionById -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Close-SS6Sessions' {
        It 'Test Close-SS6Sessions' {
            #$TestResult = Close-SS6Sessions
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-SS6CSR' {
        It 'Test New-SS6CSR' {
            #$TestResult = New-SS6CSR -CSR "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteBlockListConfig' {
        It 'Test Invoke-SS6DeleteBlockListConfig' {
            #$TestResult = Invoke-SS6DeleteBlockListConfig -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteCSR' {
        It 'Test Invoke-SS6DeleteCSR' {
            #$TestResult = Invoke-SS6DeleteCSR -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteFTPCertByID' {
        It 'Test Invoke-SS6DeleteFTPCertByID' {
            #$TestResult = Invoke-SS6DeleteFTPCertByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteLDAPConfig' {
        It 'Test Invoke-SS6DeleteLDAPConfig' {
            #$TestResult = Invoke-SS6DeleteLDAPConfig -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeletePublicKey' {
        It 'Test Invoke-SS6DeletePublicKey' {
            #$TestResult = Invoke-SS6DeletePublicKey -Id "TEST_VALUE" -KeyID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteSSHHostKeyByID' {
        It 'Test Invoke-SS6DeleteSSHHostKeyByID' {
            #$TestResult = Invoke-SS6DeleteSSHHostKeyByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteScript' {
        It 'Test Invoke-SS6DeleteScript' {
            #$TestResult = Invoke-SS6DeleteScript -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteUser' {
        It 'Test Invoke-SS6DeleteUser' {
            #$TestResult = Invoke-SS6DeleteUser -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6DeleteVFS' {
        It 'Test Invoke-SS6DeleteVFS' {
            #$TestResult = Invoke-SS6DeleteVFS -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-SS6Cert' {
        It 'Test New-SS6Cert' {
            #$TestResult = New-SS6Cert -CertificateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-SS6SSHHostKey' {
        It 'Test New-SS6SSHHostKey' {
            #$TestResult = New-SS6SSHHostKey -HostKeyRequestFields "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-SS6UserPublicKeys' {
        It 'Test New-SS6UserPublicKeys' {
            #$TestResult = New-SS6UserPublicKeys -Id "TEST_VALUE" -HostKeyRequestFields "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6ActiveSessions' {
        It 'Test Get-SS6ActiveSessions' {
            #$TestResult = Get-SS6ActiveSessions
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6AdminNotification' {
        It 'Test Get-SS6AdminNotification' {
            #$TestResult = Get-SS6AdminNotification -From "TEST_VALUE" -To "TEST_VALUE" -Limit "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6AdminNotificationByID' {
        It 'Test Get-SS6AdminNotificationByID' {
            #$TestResult = Get-SS6AdminNotificationByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6AdminProfile' {
        It 'Test Get-SS6AdminProfile' {
            #$TestResult = Get-SS6AdminProfile
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6BlockListConfig' {
        It 'Test Get-SS6BlockListConfig' {
            #$TestResult = Get-SS6BlockListConfig -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6BlockLists' {
        It 'Test Get-SS6BlockLists' {
            #$TestResult = Get-SS6BlockLists -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6CSR' {
        It 'Test Get-SS6CSR' {
            #$TestResult = Get-SS6CSR -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6CSRs' {
        It 'Test Get-SS6CSRs' {
            #$TestResult = Get-SS6CSRs
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6CertByID' {
        It 'Test Get-SS6CertByID' {
            #$TestResult = Get-SS6CertByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6Certs' {
        It 'Test Get-SS6Certs' {
            #$TestResult = Get-SS6Certs
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6GlobalStats' {
        It 'Test Get-SS6GlobalStats' {
            #$TestResult = Get-SS6GlobalStats
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6LDAPConfig' {
        It 'Test Get-SS6LDAPConfig' {
            #$TestResult = Get-SS6LDAPConfig -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6LDAPConfigs' {
        It 'Test Get-SS6LDAPConfigs' {
            #$TestResult = Get-SS6LDAPConfigs -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SSHHostKeyByID' {
        It 'Test Get-SS6SSHHostKeyByID' {
            #$TestResult = Get-SS6SSHHostKeyByID -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SSHHostKeys' {
        It 'Test Get-SS6SSHHostKeys' {
            #$TestResult = Get-SS6SSHHostKeys
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6Scrips' {
        It 'Test Get-SS6Scrips' {
            #$TestResult = Get-SS6Scrips -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6Scripts' {
        It 'Test Get-SS6Scripts' {
            #$TestResult = Get-SS6Scripts -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6StatsSinceLastStart' {
        It 'Test Get-SS6StatsSinceLastStart' {
            #$TestResult = Get-SS6StatsSinceLastStart
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SystemProperties' {
        It 'Test Get-SS6SystemProperties' {
            #$TestResult = Get-SS6SystemProperties
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6User' {
        It 'Test Get-SS6User' {
            #$TestResult = Get-SS6User -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6UserPublicKeyByID' {
        It 'Test Get-SS6UserPublicKeyByID' {
            #$TestResult = Get-SS6UserPublicKeyByID -Id "TEST_VALUE" -KeyID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6UserPublicKeys' {
        It 'Test Get-SS6UserPublicKeys' {
            #$TestResult = Get-SS6UserPublicKeys -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6Users' {
        It 'Test Get-SS6Users' {
            #$TestResult = Get-SS6Users -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6VFS' {
        It 'Test Get-SS6VFS' {
            #$TestResult = Get-SS6VFS -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6VFSs' {
        It 'Test Get-SS6VFSs' {
            #$TestResult = Get-SS6VFSs -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6VsiteConfig' {
        It 'Test Get-SS6VsiteConfig' {
            #$TestResult = Get-SS6VsiteConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6ParchVsiteConfig' {
        It 'Test Invoke-SS6ParchVsiteConfig' {
            #$TestResult = Invoke-SS6ParchVsiteConfig -SrvConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6PatchLDAPConfig' {
        It 'Test Invoke-SS6PatchLDAPConfig' {
            #$TestResult = Invoke-SS6PatchLDAPConfig -Id "TEST_VALUE" -LDAPConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6PatchScript' {
        It 'Test Invoke-SS6PatchScript' {
            #$TestResult = Invoke-SS6PatchScript -Id "TEST_VALUE" -Script "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6PatchUser' {
        It 'Test Invoke-SS6PatchUser' {
            #$TestResult = Invoke-SS6PatchUser -Id "TEST_VALUE" -User "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6PatchVFS' {
        It 'Test Invoke-SS6PatchVFS' {
            #$TestResult = Invoke-SS6PatchVFS -Id "TEST_VALUE" -VirtualFileSystem "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6AdminPassword' {
        It 'Test Update-SS6AdminPassword' {
            #$TestResult = Update-SS6AdminPassword -PasswordType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6LDAPConfig' {
        It 'Test Update-SS6LDAPConfig' {
            #$TestResult = Update-SS6LDAPConfig -Id "TEST_VALUE" -LDAPConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6Script' {
        It 'Test Update-SS6Script' {
            #$TestResult = Update-SS6Script -Id "TEST_VALUE" -Script "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6User' {
        It 'Test Update-SS6User' {
            #$TestResult = Update-SS6User -Id "TEST_VALUE" -User "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6VFS' {
        It 'Test Update-SS6VFS' {
            #$TestResult = Update-SS6VFS -Id "TEST_VALUE" -VirtualFileSystem "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6VsiteConfig' {
        It 'Test Update-SS6VsiteConfig' {
            #$TestResult = Update-SS6VsiteConfig -SrvConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-SS6VsiteConfigMode' {
        It 'Test Update-SS6VsiteConfigMode' {
            #$TestResult = Update-SS6VsiteConfigMode -Mode "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
