#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6MiscApi' {
    Context 'Get-SS6Version' {
        It 'Test Get-SS6Version' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

}
