#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SS6ResourcesApi' {
    Context 'Get-SS6VSiteDisclaimer' {
        It 'Test Get-SS6VSiteDisclaimer' {
            #$TestResult = Get-SS6VSiteDisclaimer -VsiteID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6VSiteLogo' {
        It 'Test Get-SS6VSiteLogo' {
            #$TestResult = Get-SS6VSiteLogo -VsiteID "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
