#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SS6SetupApi' {
    Context 'New-SS6SA' {
        It 'Test New-SS6SA' {
            #$TestResult = New-SS6SA -XSetupOTP "TEST_VALUE" -SuperAdmin "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SetupQRCodePng' {
        It 'Test Get-SS6SetupQRCodePng' {
            #$TestResult = Get-SS6SetupQRCodePng -Issuer "TEST_VALUE" -Email "TEST_VALUE" -Secret "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SetupRandomBase32' {
        It 'Test Get-SS6SetupRandomBase32' {
            #$TestResult = Get-SS6SetupRandomBase32 -Length "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-SS6SetupRandomName' {
        It 'Test Get-SS6SetupRandomName' {
            #$TestResult = Get-SS6SetupRandomName
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-SS6Googleauthenticatortest' {
        It 'Test Invoke-SS6Googleauthenticatortest' {
            #$TestResult = Invoke-SS6Googleauthenticatortest -Secret "TEST_VALUE" -Token "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Join-SS6HANode' {
        It 'Test Join-SS6HANode' {
            #$TestResult = Join-SS6HANode -XSetupOTP "TEST_VALUE" -InlineObject1 "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-SS6Node' {
        It 'Test Set-SS6Node' {
            #$TestResult = Set-SS6Node -XSetupOTP "TEST_VALUE" -Node "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-SS6SSC' {
        It 'Test Set-SS6SSC' {
            #$TestResult = Set-SS6SSC -InlineObject "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
