#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SuperAdminApi' {
    Context 'Add-SS6Admin' {
        It 'Test Add-SS6Admin' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -Admin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Add-SS6NodeCRTToCSR' {
        It 'Test Add-SS6NodeCRTToCSR' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -InlineObject2 "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Add-SS6NodeCertificate' {
        It 'Test Add-SS6NodeCertificate' {
            #$TestResult = Invoke-PetApiGetPetById -NodeCertificate "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Add-SS6SuperAdmin' {
        It 'Test Add-SS6SuperAdmin' {
            #$TestResult = Invoke-PetApiGetPetById -SuperAdmin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Add-SS6Vsite' {
        It 'Test Add-SS6Vsite' {
            #$TestResult = Invoke-PetApiGetPetById -VirtualSite "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6CreateNodeCSR' {
        It 'Test Invoke-SS6CreateNodeCSR' {
            #$TestResult = Invoke-PetApiGetPetById -CSR "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6DeleteAdmin' {
        It 'Test Invoke-SS6DeleteAdmin' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -AdminID "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6DeleteNodeCSR' {
        It 'Test Invoke-SS6DeleteNodeCSR' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6DeleteNodeCertificate' {
        It 'Test Invoke-SS6DeleteNodeCertificate' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6DeleteSuperAdminByID' {
        It 'Test Invoke-SS6DeleteSuperAdminByID' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6DeleteVsite' {
        It 'Test Invoke-SS6DeleteVsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6GenerateNodeCert' {
        It 'Test Invoke-SS6GenerateNodeCert' {
            #$TestResult = Invoke-PetApiGetPetById -CertificateRequest "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6Admin' {
        It 'Test Get-SS6Admin' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -AdminID "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6Admins' {
        It 'Test Get-SS6Admins' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6AvailableBindings' {
        It 'Test Get-SS6AvailableBindings' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6Node' {
        It 'Test Get-SS6Node' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6NodeCSR' {
        It 'Test Get-SS6NodeCSR' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6NodeCSRs' {
        It 'Test Get-SS6NodeCSRs' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6NodeCertifcates' {
        It 'Test Get-SS6NodeCertifcates' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6NodeCertificate' {
        It 'Test Get-SS6NodeCertificate' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6QRCodePng' {
        It 'Test Get-SS6QRCodePng' {
            #$TestResult = Invoke-PetApiGetPetById -Issuer "TEST_VALUE" -Email "TEST_VALUE" -Secret "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6RandomBase32' {
        It 'Test Get-SS6RandomBase32' {
            #$TestResult = Invoke-PetApiGetPetById -Length "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6RandomName' {
        It 'Test Get-SS6RandomName' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6SuperAdminByID' {
        It 'Test Get-SS6SuperAdminByID' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6SuperAdmins' {
        It 'Test Get-SS6SuperAdmins' {
            #$TestResult = Invoke-PetApiGetPetById -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6Vsite' {
        It 'Test Get-SS6Vsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Get-SS6Vsites' {
        It 'Test Get-SS6Vsites' {
            #$TestResult = Invoke-PetApiGetPetById -Offset "TEST_VALUE" -Limit "TEST_VALUE" -Order "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6Googleauthenticatortestsa' {
        It 'Test Invoke-SS6Googleauthenticatortestsa' {
            #$TestResult = Invoke-PetApiGetPetById -Secret "TEST_VALUE" -Token "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6PatchAdmin' {
        It 'Test Invoke-SS6PatchAdmin' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -AdminID "TEST_VALUE" -Admin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6PatchNode' {
        It 'Test Invoke-SS6PatchNode' {
            #$TestResult = Invoke-PetApiGetPetById -Node "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6PatchSuperAdminByID' {
        It 'Test Invoke-SS6PatchSuperAdminByID' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -SuperAdmin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6PatchVsite' {
        It 'Test Invoke-SS6PatchVsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -VirtualSite "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6SaBackup' {
        It 'Test Invoke-SS6SaBackup' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6SaLogin' {
        It 'Test Invoke-SS6SaLogin' {
            #$TestResult = Invoke-PetApiGetPetById -X_OTP "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6SaLogout' {
        It 'Test Invoke-SS6SaLogout' {
            #$TestResult = Invoke-PetApiGetPetById
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Invoke-SS6SaRestore' {
        It 'Test Invoke-SS6SaRestore' {
            #$TestResult = Invoke-PetApiGetPetById -Filename "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Start-SS6Vsite' {
        It 'Test Start-SS6Vsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Stop-SS6Vsite' {
        It 'Test Stop-SS6Vsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-SS6Admin' {
        It 'Test Update-SS6Admin' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -AdminID "TEST_VALUE" -Admin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-SS6Node' {
        It 'Test Update-SS6Node' {
            #$TestResult = Invoke-PetApiGetPetById -Node "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-SS6SAPassword' {
        It 'Test Update-SS6SAPassword' {
            #$TestResult = Invoke-PetApiGetPetById -PasswordType "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-SS6SuperAdminByID' {
        It 'Test Update-SS6SuperAdminByID' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -SuperAdmin "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

    Context 'Update-SS6Vsite' {
        It 'Test Update-SS6Vsite' {
            #$TestResult = Invoke-PetApiGetPetById -Id "TEST_VALUE" -VirtualSite "TEST_VALUE"
            #$TestResult | Should BeOfType TODO
            #$TestResult.property | Should Be 0
        }
    }

}
