#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'AccountStatus' {
    Context 'AccountStatus' {
        It 'New-AccountStatus' {
            # a simple test to create an object
            #$NewObject = New-AccountStatus
            #$NewObject | Should BeOfType AccountStatus
            #$NewObject.property | Should Be 0
        }
    }
}
