#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'AdminConfigObjects' {
    Context 'AdminConfigObjects' {
        It 'New-AdminConfigObjects' {
            # a simple test to create an object
            #$NewObject = New-AdminConfigObjects
            #$NewObject | Should BeOfType AdminConfigObjects
            #$NewObject.property | Should Be 0
        }
    }
}
