#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6Admin' {
    Context 'SS6Admin' {
        It 'Initialize-SS6Admin' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6Admin -Id "TEST_VALUE" -Password "TEST_VALUE" -Email "TEST_VALUE" -Permissions "TEST_VALUE" -Picture "TEST_VALUE" -Status "TEST_VALUE" -AutoDisable "TEST_VALUE" -AutoDisableDate "TEST_VALUE" -AllowList "TEST_VALUE" -TourTaken "TEST_VALUE" -ReceiveEmailNotifications "TEST_VALUE" -AuthenticatorSecret "TEST_VALUE" -AuthenticatorType "TEST_VALUE"
            #$NewObject | Should -BeOfType Admin
            #$NewObject.property | Should -Be 0
        }
    }
}
