#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'Admin' {
    Context 'Admin' {
        It 'New-Admin' {
            # a simple test to create an object
            #$NewObject = New-Admin -Id "TEST_VALUE" -Password "TEST_VALUE" -Email "TEST_VALUE" -Permissions "TEST_VALUE" -Picture "TEST_VALUE" -Status "TEST_VALUE" -AutoDisable "TEST_VALUE" -AutoDisableDate "TEST_VALUE" -AllowList "TEST_VALUE"
            #$NewObject | Should BeOfType Admin
            #$NewObject.property | Should Be 0
        }
    }
}
