#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6AdminPerm' {
    Context 'SS6AdminPerm' {
        It 'Initialize-SS6AdminPerm' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6AdminPerm -View "TEST_VALUE" -Edit "TEST_VALUE"
            #$NewObject | Should -BeOfType AdminPerm
            #$NewObject.property | Should -Be 0
        }
    }
}
