#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6ApiError' {
    Context 'SS6ApiError' {
        It 'Initialize-SS6ApiError' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6ApiError -ErrorType "TEST_VALUE" -VarData "TEST_VALUE" -Reason "TEST_VALUE" -CausedBy "TEST_VALUE" -HumanReadable "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiError
            #$NewObject.property | Should -Be 0
        }
    }
}
