#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6ApiResponse' {
    Context 'SS6ApiResponse' {
        It 'Initialize-SS6ApiResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6ApiResponse -Message "TEST_VALUE" -Errors "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
