#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'Authenticator' {
    Context 'Authenticator' {
        It 'Initialize-Authenticator' {
            # a simple test to create an object
            #$NewObject = Initialize-Authenticator
            #$NewObject | Should -BeOfType Authenticator
            #$NewObject.property | Should -Be 0
        }
    }
}
