#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'Authenticator' {
    Context 'Authenticator' {
        It 'New-Authenticator' {
            # a simple test to create an object
            #$NewObject = New-Authenticator
            #$NewObject | Should BeOfType Authenticator
            #$NewObject.property | Should Be 0
        }
    }
}
