#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'AuthType' {
    Context 'AuthType' {
        It 'New-AuthType' {
            # a simple test to create an object
            #$NewObject = New-AuthType
            #$NewObject | Should BeOfType AuthType
            #$NewObject.property | Should Be 0
        }
    }
}
