#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'BehaviorType' {
    Context 'BehaviorType' {
        It 'New-BehaviorType' {
            # a simple test to create an object
            #$NewObject = New-BehaviorType
            #$NewObject | Should BeOfType BehaviorType
            #$NewObject.property | Should Be 0
        }
    }
}
