#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'CertificateBaseFields' {
    Context 'CertificateBaseFields' {
        It 'Initialize-CertificateBaseFields' {
            # a simple test to create an object
            #$NewObject = Initialize-CertificateBaseFields -CommonName "TEST_VALUE" -Country "TEST_VALUE" -Organization "TEST_VALUE" -OrganizationalUnit "TEST_VALUE" -Locality "TEST_VALUE" -Province "TEST_VALUE" -Bits "TEST_VALUE" -Algo "TEST_VALUE" -Hosts "TEST_VALUE"
            #$NewObject | Should -BeOfType CertificateBaseFields
            #$NewObject.property | Should -Be 0
        }
    }
}
