#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'CipherSuites' {
    Context 'CipherSuites' {
        It 'New-CipherSuites' {
            # a simple test to create an object
            #$NewObject = New-CipherSuites
            #$NewObject | Should BeOfType CipherSuites
            #$NewObject.property | Should Be 0
        }
    }
}
