#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6CORSConfig' {
    Context 'SS6CORSConfig' {
        It 'Initialize-SS6CORSConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6CORSConfig -Enable "TEST_VALUE" -Origins "TEST_VALUE" -ValidateHeaders "TEST_VALUE" -RequestHeaders "TEST_VALUE" -ExposedHeaders "TEST_VALUE" -Methods "TEST_VALUE" -MaxAgeMinutes "TEST_VALUE"
            #$NewObject | Should -BeOfType CORSConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
