#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6CSRAllOf' {
    Context 'SS6CSRAllOf' {
        It 'Initialize-SS6CSRAllOf' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6CSRAllOf -Id "TEST_VALUE" -EmailAddress "TEST_VALUE" -UriList "TEST_VALUE" -SigningReq "TEST_VALUE"
            #$NewObject | Should -BeOfType CSRAllOf
            #$NewObject.property | Should -Be 0
        }
    }
}
