#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'ErrorType' {
    Context 'ErrorType' {
        It 'New-ErrorType' {
            # a simple test to create an object
            #$NewObject = New-ErrorType
            #$NewObject | Should BeOfType ErrorType
            #$NewObject.property | Should Be 0
        }
    }
}
