#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'EventType' {
    Context 'EventType' {
        It 'New-EventType' {
            # a simple test to create an object
            #$NewObject = New-EventType
            #$NewObject | Should BeOfType EventType
            #$NewObject.property | Should Be 0
        }
    }
}
