#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'EventHandler' {
    Context 'EventHandler' {
        It 'Initialize-EventHandler' {
            # a simple test to create an object
            #$NewObject = Initialize-EventHandler -VarEvent "TEST_VALUE" -Script "TEST_VALUE" -Priority "TEST_VALUE" -ExecTimeoutSecs "TEST_VALUE"
            #$NewObject | Should -BeOfType EventHandler
            #$NewObject.property | Should -Be 0
        }
    }
}
