#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6GlobalConfig' {
    Context 'SS6GlobalConfig' {
        It 'Initialize-SS6GlobalConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6GlobalConfig -Id "TEST_VALUE" -SmtpConf "TEST_VALUE" -LogConf "TEST_VALUE" -SecurityConf "TEST_VALUE" -CorsConf "TEST_VALUE" -JwtLifeSpan "TEST_VALUE" -JwtAutoRefresh "TEST_VALUE" -JwtAutoRefreshMaxTimes "TEST_VALUE"
            #$NewObject | Should -BeOfType GlobalConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
