#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6HAVsiteStatus' {
    Context 'SS6HAVsiteStatus' {
        It 'Initialize-SS6HAVsiteStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6HAVsiteStatus -Id "TEST_VALUE" -Nodes "TEST_VALUE"
            #$NewObject | Should -BeOfType HAVsiteStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
