#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'HostKeyRequestFields' {
    Context 'HostKeyRequestFields' {
        It 'Initialize-HostKeyRequestFields' {
            # a simple test to create an object
            #$NewObject = Initialize-HostKeyRequestFields -Name "TEST_VALUE" -Type "TEST_VALUE" -Bits "TEST_VALUE"
            #$NewObject | Should -BeOfType HostKeyRequestFields
            #$NewObject.property | Should -Be 0
        }
    }
}
