#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'HTTPSConfig' {
    Context 'HTTPSConfig' {
        It 'Initialize-HTTPSConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-HTTPSConfig -Certificates "TEST_VALUE" -MinTlsVersion "TEST_VALUE" -MaxTlsVersion "TEST_VALUE" -AllowedCipherSuites "TEST_VALUE" -JwtLifeSpan "TEST_VALUE" -JwtSecretWc "TEST_VALUE" -JwtSecretShare "TEST_VALUE" -JwtAutoRefresh "TEST_VALUE" -JwtAutoRefreshMaxTimes "TEST_VALUE" -TrustedProxies "TEST_VALUE" -SecurityConf "TEST_VALUE" -CorsConf "TEST_VALUE" -WebClientRateLimit "TEST_VALUE" -MaxUploadSize "TEST_VALUE" -MaxZipFiles "TEST_VALUE" -MaxZipDataSize "TEST_VALUE" -WebClientUiLogo "TEST_VALUE" -WebClientUiLogoType "TEST_VALUE" -WebClientUiDisclaimer "TEST_VALUE"
            #$NewObject | Should -BeOfType HTTPSConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
