#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'HTTPSConfig' {
    Context 'HTTPSConfig' {
        It 'New-HTTPSConfig' {
            # a simple test to create an object
            #$NewObject = New-HTTPSConfig -MinTlsVersion "TEST_VALUE" -MaxTlsVersion "TEST_VALUE" -AllowedCipherSuites "TEST_VALUE"
            #$NewObject | Should BeOfType HTTPSConfig
            #$NewObject.property | Should Be 0
        }
    }
}
