#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6InlineObject1' {
    Context 'SS6InlineObject1' {
        It 'Initialize-SS6InlineObject1' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6InlineObject1 -RemoteAddr "TEST_VALUE" -Username "TEST_VALUE" -Password "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineObject1
            #$NewObject.property | Should -Be 0
        }
    }
}
