#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'InlineResponse2003' {
    Context 'InlineResponse2003' {
        It 'New-InlineResponse2003' {
            # a simple test to create an object
            #$NewObject = New-InlineResponse2003 -Key "TEST_VALUE"
            #$NewObject | Should BeOfType InlineResponse2003
            #$NewObject.property | Should Be 0
        }
    }
}
