#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'InlineObject5' {
    Context 'InlineObject5' {
        It 'Initialize-InlineObject5' {
            # a simple test to create an object
            #$NewObject = Initialize-InlineObject5 -Payload "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineObject5
            #$NewObject.property | Should -Be 0
        }
    }
}
