#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'InlineResponse200' {
    Context 'InlineResponse200' {
        It 'New-InlineResponse200' {
            # a simple test to create an object
            #$NewObject = New-InlineResponse200 -Totp "TEST_VALUE"
            #$NewObject | Should BeOfType InlineResponse200
            #$NewObject.property | Should Be 0
        }
    }
}
