#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'InlineObject3' {
    Context 'InlineObject3' {
        It 'New-InlineObject3' {
            # a simple test to create an object
            #$NewObject = New-InlineObject3 -Cert "TEST_VALUE"
            #$NewObject | Should BeOfType InlineObject3
            #$NewObject.property | Should Be 0
        }
    }
}
