#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'InlineResponse2002' {
    Context 'InlineResponse2002' {
        It 'New-InlineResponse2002' {
            # a simple test to create an object
            #$NewObject = New-InlineResponse2002 -Code "TEST_VALUE"
            #$NewObject | Should BeOfType InlineResponse2002
            #$NewObject.property | Should Be 0
        }
    }
}
