#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6InlineObject4' {
    Context 'SS6InlineObject4' {
        It 'Initialize-SS6InlineObject4' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6InlineObject4 -Code "TEST_VALUE"
            #$NewObject | Should -BeOfType InlineObject4
            #$NewObject.property | Should -Be 0
        }
    }
}
