#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'LDAPProto' {
    Context 'LDAPProto' {
        It 'New-LDAPProto' {
            # a simple test to create an object
            #$NewObject = New-LDAPProto
            #$NewObject | Should BeOfType LDAPProto
            #$NewObject.property | Should Be 0
        }
    }
}
