#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'LDAPConfig' {
    Context 'LDAPConfig' {
        It 'Initialize-LDAPConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-LDAPConfig -Id "TEST_VALUE" -Port "TEST_VALUE" -LdapProto "TEST_VALUE" -Username "TEST_VALUE" -Password "TEST_VALUE" -Domains "TEST_VALUE"
            #$NewObject | Should -BeOfType LDAPConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
