#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6License' {
    Context 'SS6License' {
        It 'Initialize-SS6License' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6License -Code "TEST_VALUE" -SemVerConstraint "TEST_VALUE" -ValidFrom "TEST_VALUE" -ValidTo "TEST_VALUE" -Customer "TEST_VALUE" -SystemdID "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType License
            #$NewObject.property | Should -Be 0
        }
    }
}
