#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6LogConfig' {
    Context 'SS6LogConfig' {
        It 'Initialize-SS6LogConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6LogConfig -To "TEST_VALUE" -Detail "TEST_VALUE" -CfgToStdout "TEST_VALUE" -CfgToFile "TEST_VALUE" -CfgToDb "TEST_VALUE" -CfgToSyslog "TEST_VALUE"
            #$NewObject | Should -BeOfType LogConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
