#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'LogDetailType' {
    Context 'LogDetailType' {
        It 'New-LogDetailType' {
            # a simple test to create an object
            #$NewObject = New-LogDetailType
            #$NewObject | Should BeOfType LogDetailType
            #$NewObject.property | Should Be 0
        }
    }
}
