#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6LogDetailType' {
    Context 'SS6LogDetailType' {
        It 'Initialize-SS6LogDetailType' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6LogDetailType
            #$NewObject | Should -BeOfType LogDetailType
            #$NewObject.property | Should -Be 0
        }
    }
}
