#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'LogToDatabaseCfg' {
    Context 'LogToDatabaseCfg' {
        It 'Initialize-LogToDatabaseCfg' {
            # a simple test to create an object
            #$NewObject = Initialize-LogToDatabaseCfg -SameAsServer "TEST_VALUE" -DbUri "TEST_VALUE" -User "TEST_VALUE" -Pass "TEST_VALUE"
            #$NewObject | Should -BeOfType LogToDatabaseCfg
            #$NewObject.property | Should -Be 0
        }
    }
}
