#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'LogToSyslogCfg' {
    Context 'LogToSyslogCfg' {
        It 'Initialize-LogToSyslogCfg' {
            # a simple test to create an object
            #$NewObject = Initialize-LogToSyslogCfg -Network "TEST_VALUE" -Address "TEST_VALUE" -Tag "TEST_VALUE" -Marker "TEST_VALUE"
            #$NewObject | Should -BeOfType LogToSyslogCfg
            #$NewObject.property | Should -Be 0
        }
    }
}
