#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6LogToStdoutCfg' {
    Context 'SS6LogToStdoutCfg' {
        It 'Initialize-SS6LogToStdoutCfg' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6LogToStdoutCfg -ColorOutput "TEST_VALUE"
            #$NewObject | Should -BeOfType LogToStdoutCfg
            #$NewObject.property | Should -Be 0
        }
    }
}
