#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'Node' {
    Context 'Node' {
        It 'New-Node' {
            # a simple test to create an object
            #$NewObject = New-Node -Id "TEST_VALUE" -Description "TEST_VALUE" -Secret "TEST_VALUE"
            #$NewObject | Should BeOfType Node
            #$NewObject.property | Should Be 0
        }
    }
}
