#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6NodeBinding' {
    Context 'SS6NodeBinding' {
        It 'Initialize-SS6NodeBinding' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6NodeBinding -NodeId "TEST_VALUE" -Bindings "TEST_VALUE"
            #$NewObject | Should -BeOfType NodeBinding
            #$NewObject.property | Should -Be 0
        }
    }
}
