#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6Node' {
    Context 'SS6Node' {
        It 'Initialize-SS6Node' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6Node -Id "TEST_VALUE" -Description "TEST_VALUE" -PrivateKey "TEST_VALUE" -PublicKey "TEST_VALUE"
            #$NewObject | Should -BeOfType Node
            #$NewObject.property | Should -Be 0
        }
    }
}
