#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6NodeStatus' {
    Context 'SS6NodeStatus' {
        It 'Initialize-SS6NodeStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6NodeStatus -Id "TEST_VALUE" -RestServiceStatus "TEST_VALUE" -WorkerServiceStatus "TEST_VALUE"
            #$NewObject | Should -BeOfType NodeStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
