#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'NotificationKind' {
    Context 'NotificationKind' {
        It 'Initialize-NotificationKind' {
            # a simple test to create an object
            #$NewObject = Initialize-NotificationKind
            #$NewObject | Should -BeOfType NotificationKind
            #$NewObject.property | Should -Be 0
        }
    }
}
