#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PasswordType' {
    Context 'PasswordType' {
        It 'Initialize-PasswordType' {
            # a simple test to create an object
            #$NewObject = Initialize-PasswordType -Version "TEST_VALUE" -Salt "TEST_VALUE" -Payload "TEST_VALUE" -MustChange "TEST_VALUE"
            #$NewObject | Should -BeOfType PasswordType
            #$NewObject.property | Should -Be 0
        }
    }
}
