#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PermOverrider' {
    Context 'PermOverrider' {
        It 'New-PermOverrider' {
            # a simple test to create an object
            #$NewObject = New-PermOverrider -Permissions "TEST_VALUE"
            #$NewObject | Should BeOfType PermOverrider
            #$NewObject.property | Should Be 0
        }
    }
}
