#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PersistenceType' {
    Context 'PersistenceType' {
        It 'New-PersistenceType' {
            # a simple test to create an object
            #$NewObject = New-PersistenceType
            #$NewObject | Should BeOfType PersistenceType
            #$NewObject.property | Should Be 0
        }
    }
}
