#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PersistenceType' {
    Context 'PersistenceType' {
        It 'Initialize-PersistenceType' {
            # a simple test to create an object
            #$NewObject = Initialize-PersistenceType
            #$NewObject | Should -BeOfType PersistenceType
            #$NewObject.property | Should -Be 0
        }
    }
}
