#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PictureKind' {
    Context 'PictureKind' {
        It 'New-PictureKind' {
            # a simple test to create an object
            #$NewObject = New-PictureKind
            #$NewObject | Should BeOfType PictureKind
            #$NewObject.property | Should Be 0
        }
    }
}
