#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'PictureType' {
    Context 'PictureType' {
        It 'Initialize-PictureType' {
            # a simple test to create an object
            #$NewObject = Initialize-PictureType -Kind "TEST_VALUE" -IdIfBuiltIn "TEST_VALUE" -Base64IfCustom "TEST_VALUE"
            #$NewObject | Should -BeOfType PictureType
            #$NewObject.property | Should -Be 0
        }
    }
}
