#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SAListItem' {
    Context 'SAListItem' {
        It 'New-SAListItem' {
            # a simple test to create an object
            #$NewObject = New-SAListItem -IpOrNetwork "TEST_VALUE" -Notes "TEST_VALUE"
            #$NewObject | Should BeOfType SAListItem
            #$NewObject.property | Should Be 0
        }
    }
}
