#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6Secret' {
    Context 'SS6Secret' {
        It 'Initialize-SS6Secret' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6Secret -Status "TEST_VALUE" -Payload "TEST_VALUE"
            #$NewObject | Should -BeOfType Secret
            #$NewObject.property | Should -Be 0
        }
    }
}
