#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SecretStatus' {
    Context 'SecretStatus' {
        It 'Initialize-SecretStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-SecretStatus
            #$NewObject | Should -BeOfType SecretStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
