#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'Secret' {
    Context 'Secret' {
        It 'New-Secret' {
            # a simple test to create an object
            #$NewObject = New-Secret -Status "TEST_VALUE" -Payload "TEST_VALUE"
            #$NewObject | Should BeOfType Secret
            #$NewObject.property | Should Be 0
        }
    }
}
