#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'ServiceType' {
    Context 'ServiceType' {
        It 'New-ServiceType' {
            # a simple test to create an object
            #$NewObject = New-ServiceType
            #$NewObject | Should BeOfType ServiceType
            #$NewObject.property | Should Be 0
        }
    }
}
