#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'ServiceStatus' {
    Context 'ServiceStatus' {
        It 'Initialize-ServiceStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-ServiceStatus
            #$NewObject | Should -BeOfType ServiceStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
