#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SFTPVersions' {
    Context 'SFTPVersions' {
        It 'Initialize-SFTPVersions' {
            # a simple test to create an object
            #$NewObject = Initialize-SFTPVersions
            #$NewObject | Should -BeOfType SFTPVersions
            #$NewObject.property | Should -Be 0
        }
    }
}
