#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SMTPConfig' {
    Context 'SMTPConfig' {
        It 'Initialize-SMTPConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-SMTPConfig -VarHost "TEST_VALUE" -Port "TEST_VALUE" -VarSender "TEST_VALUE" -User "TEST_VALUE" -Pass "TEST_VALUE" -TlsCliMode "TEST_VALUE"
            #$NewObject | Should -BeOfType SMTPConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
