#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SMTPConfig' {
    Context 'SMTPConfig' {
        It 'New-SMTPConfig' {
            # a simple test to create an object
            #$NewObject = New-SMTPConfig -Host "TEST_VALUE" -Port "TEST_VALUE" -Sender "TEST_VALUE" -User "TEST_VALUE" -Pass "TEST_VALUE" -TlsCliMode "TEST_VALUE"
            #$NewObject | Should BeOfType SMTPConfig
            #$NewObject.property | Should Be 0
        }
    }
}
