#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SpeedLimit' {
    Context 'SpeedLimit' {
        It 'Initialize-SpeedLimit' {
            # a simple test to create an object
            #$NewObject = Initialize-SpeedLimit -Source "TEST_VALUE" -UpKbps "TEST_VALUE" -DnKbps "TEST_VALUE"
            #$NewObject | Should -BeOfType SpeedLimit
            #$NewObject.property | Should -Be 0
        }
    }
}
