#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHAuths' {
    Context 'SSHAuths' {
        It 'Initialize-SSHAuths' {
            # a simple test to create an object
            #$NewObject = Initialize-SSHAuths
            #$NewObject | Should -BeOfType SSHAuths
            #$NewObject.property | Should -Be 0
        }
    }
}
