#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SSHConfig' {
    Context 'SS6SSHConfig' {
        It 'Initialize-SS6SSHConfig' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6SSHConfig -SoftwareId "TEST_VALUE" -Greeting "TEST_VALUE" -ZCompress "TEST_VALUE" -UseAllocator "TEST_VALUE" -AssumeUtf8 "TEST_VALUE" -OverrideTimeout "TEST_VALUE" -AllowForwardingTo "TEST_VALUE" -SftpVer "TEST_VALUE" -Auth "TEST_VALUE" -Kex "TEST_VALUE" -Mac "TEST_VALUE" -Crypto "TEST_VALUE"
            #$NewObject | Should -BeOfType SSHConfig
            #$NewObject.property | Should -Be 0
        }
    }
}
