#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHCrypto' {
    Context 'SSHCrypto' {
        It 'New-SSHCrypto' {
            # a simple test to create an object
            #$NewObject = New-SSHCrypto
            #$NewObject | Should BeOfType SSHCrypto
            #$NewObject.property | Should Be 0
        }
    }
}
