#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHECDSAKeyBits' {
    Context 'SSHECDSAKeyBits' {
        It 'Initialize-SSHECDSAKeyBits' {
            # a simple test to create an object
            #$NewObject = Initialize-SSHECDSAKeyBits
            #$NewObject | Should -BeOfType SSHECDSAKeyBits
            #$NewObject.property | Should -Be 0
        }
    }
}
