#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SSHHostKey' {
    Context 'SS6SSHHostKey' {
        It 'Initialize-SS6SSHHostKey' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6SSHHostKey -Id "TEST_VALUE" -Name "TEST_VALUE" -Key "TEST_VALUE" -Type "TEST_VALUE" -Fingerprint "TEST_VALUE"
            #$NewObject | Should -BeOfType SSHHostKey
            #$NewObject.property | Should -Be 0
        }
    }
}
