#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHHostKey' {
    Context 'SSHHostKey' {
        It 'New-SSHHostKey' {
            # a simple test to create an object
            #$NewObject = New-SSHHostKey -Id "TEST_VALUE" -Name "TEST_VALUE" -Key "TEST_VALUE" -Type "TEST_VALUE" -Fingerprint "TEST_VALUE"
            #$NewObject | Should BeOfType SSHHostKey
            #$NewObject.property | Should Be 0
        }
    }
}
