#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHKex' {
    Context 'SSHKex' {
        It 'Initialize-SSHKex' {
            # a simple test to create an object
            #$NewObject = Initialize-SSHKex
            #$NewObject | Should -BeOfType SSHKex
            #$NewObject.property | Should -Be 0
        }
    }
}
