#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHMac' {
    Context 'SSHMac' {
        It 'New-SSHMac' {
            # a simple test to create an object
            #$NewObject = New-SSHMac
            #$NewObject | Should BeOfType SSHMac
            #$NewObject.property | Should Be 0
        }
    }
}
