#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHPubKey' {
    Context 'SSHPubKey' {
        It 'Initialize-SSHPubKey' {
            # a simple test to create an object
            #$NewObject = Initialize-SSHPubKey -Id "TEST_VALUE" -Name "TEST_VALUE" -Key "TEST_VALUE" -Fingerprint "TEST_VALUE" -Type "TEST_VALUE" -Comment "TEST_VALUE"
            #$NewObject | Should -BeOfType SSHPubKey
            #$NewObject.property | Should -Be 0
        }
    }
}
