#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SSHRSAKeyBits' {
    Context 'SSHRSAKeyBits' {
        It 'New-SSHRSAKeyBits' {
            # a simple test to create an object
            #$NewObject = New-SSHRSAKeyBits
            #$NewObject | Should BeOfType SSHRSAKeyBits
            #$NewObject.property | Should Be 0
        }
    }
}
