#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'StatsContainer' {
    Context 'StatsContainer' {
        It 'Initialize-StatsContainer' {
            # a simple test to create an object
            #$NewObject = Initialize-StatsContainer -Started "TEST_VALUE" -SessSshShell "TEST_VALUE" -SessSshScp "TEST_VALUE" -SessSshSftp "TEST_VALUE" -SessFtp "TEST_VALUE" -SessFtps "TEST_VALUE" -SessFtpes "TEST_VALUE" -SessWebClient "TEST_VALUE" -SessWebClientShare "TEST_VALUE" -RejectedConns "TEST_VALUE" -AddedToBl "TEST_VALUE" -AddedByHammering "TEST_VALUE" -AddedByAuth "TEST_VALUE" -AddedByProtocol "TEST_VALUE" -AddedByAdmin "TEST_VALUE" -AddedByScript "TEST_VALUE" -HitsOnBl "TEST_VALUE" -HitsOnBlCache "TEST_VALUE" -FileUp "TEST_VALUE" -FileDn "TEST_VALUE" -FileUpFail "TEST_VALUE" -FileDnFail "TEST_VALUE" -TransferUpMb "TEST_VALUE" -TransferDnMb "TEST_VALUE" -ScriptsRun "TEST_VALUE"
            #$NewObject | Should -BeOfType StatsContainer
            #$NewObject.property | Should -Be 0
        }
    }
}
