#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6SystemProps' {
    Context 'SS6SystemProps' {
        It 'Initialize-SS6SystemProps' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6SystemProps -NodeId "TEST_VALUE" -RamMb "TEST_VALUE" -CpuUsage "TEST_VALUE" -System "TEST_VALUE" -Arch "TEST_VALUE" -ServiceStatus "TEST_VALUE" -ConnPeak "TEST_VALUE"
            #$NewObject | Should -BeOfType SystemProps
            #$NewObject.property | Should -Be 0
        }
    }
}
