#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6TLSCertificate' {
    Context 'SS6TLSCertificate' {
        It 'Initialize-SS6TLSCertificate' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6TLSCertificate -Id "TEST_VALUE" -Cert "TEST_VALUE" -Key "TEST_VALUE" -CaBundle "TEST_VALUE" -KeyPass "TEST_VALUE" -Hash "TEST_VALUE" -CommonName "TEST_VALUE" -ValidFrom "TEST_VALUE" -ValidUntil "TEST_VALUE"
            #$NewObject | Should -BeOfType TLSCertificate
            #$NewObject.property | Should -Be 0
        }
    }
}
