#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'TLSCertificate' {
    Context 'TLSCertificate' {
        It 'New-TLSCertificate' {
            # a simple test to create an object
            #$NewObject = New-TLSCertificate -Id "TEST_VALUE" -Cert "TEST_VALUE" -Key "TEST_VALUE" -CaBundle "TEST_VALUE" -KeyPass "TEST_VALUE" -Hash "TEST_VALUE" -CommonName "TEST_VALUE" -ValidFrom "TEST_VALUE" -ValidUntil "TEST_VALUE"
            #$NewObject | Should BeOfType TLSCertificate
            #$NewObject.property | Should Be 0
        }
    }
}
