#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'TokenObj' {
    Context 'TokenObj' {
        It 'New-TokenObj' {
            # a simple test to create an object
            #$NewObject = New-TokenObj -Token "TEST_VALUE"
            #$NewObject | Should BeOfType TokenObj
            #$NewObject.property | Should Be 0
        }
    }
}
