#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'VersionInfo' {
    Context 'VersionInfo' {
        It 'Initialize-VersionInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-VersionInfo -Name "TEST_VALUE" -Version "TEST_VALUE" -BuildDate "TEST_VALUE"
            #$NewObject | Should -BeOfType VersionInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
