#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'VFSPermissions' {
    Context 'VFSPermissions' {
        It 'New-VFSPermissions' {
            # a simple test to create an object
            #$NewObject = New-VFSPermissions
            #$NewObject | Should BeOfType VFSPermissions
            #$NewObject.property | Should Be 0
        }
    }
}
