#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'VFSQuota' {
    Context 'VFSQuota' {
        It 'New-VFSQuota' {
            # a simple test to create an object
            #$NewObject = New-VFSQuota -Soft "TEST_VALUE" -Hard "TEST_VALUE"
            #$NewObject | Should BeOfType VFSQuota
            #$NewObject.property | Should Be 0
        }
    }
}
