#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6VFSQuota' {
    Context 'SS6VFSQuota' {
        It 'Initialize-SS6VFSQuota' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6VFSQuota -Soft "TEST_VALUE" -Hard "TEST_VALUE"
            #$NewObject | Should -BeOfType VFSQuota
            #$NewObject.property | Should -Be 0
        }
    }
}
