#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'VirtualSite' {
    Context 'VirtualSite' {
        It 'Initialize-VirtualSite' {
            # a simple test to create an object
            #$NewObject = Initialize-VirtualSite -Id "TEST_VALUE" -Name "TEST_VALUE" -AutoStart "TEST_VALUE" -AutoRestart "TEST_VALUE" -ServiceStatus "TEST_VALUE" -NodeBindings "TEST_VALUE" -AdminUiLogo "TEST_VALUE" -AdminUiLogoType "TEST_VALUE" -AdminUiDisclaimer "TEST_VALUE"
            #$NewObject | Should -BeOfType VirtualSite
            #$NewObject.property | Should -Be 0
        }
    }
}
