#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'SS6AdminModule' -name 'SS6VirtualFolder' {
    Context 'SS6VirtualFolder' {
        It 'Initialize-SS6VirtualFolder' {
            # a simple test to create an object
            #$NewObject = Initialize-SS6VirtualFolder -VfsId "TEST_VALUE" -Permissions "TEST_VALUE" -Visible "TEST_VALUE"
            #$NewObject | Should -BeOfType VirtualFolder
            #$NewObject.property | Should -Be 0
        }
    }
}
