#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Event
No description available.

.PARAMETER Script
No description available.

.PARAMETER Priority
No description available.

.PARAMETER ExecTimeoutSecs
No description available.

.OUTPUTS

EventHandler<PSCustomObject>
#>

function New-SS6EventHandler {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Event},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Script},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Priority},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ExecTimeoutSecs}
    )

    Process {
        'Creating object: SS6AdminModule => SS6EventHandler' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "event" = ${Event}
            "script" = ${Script}
            "priority" = ${Priority}
            "execTimeoutSecs" = ${ExecTimeoutSecs}
        }

        return $PSO
    }
}
