#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER MinTlsVersion
No description available.

.PARAMETER MaxTlsVersion
No description available.

.PARAMETER AllowedCipherSuites
No description available.

.OUTPUTS

HTTPSConfig<PSCustomObject>
#>

function New-SS6HTTPSConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${MinTlsVersion},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${MaxTlsVersion},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AllowedCipherSuites}
    )

    Process {
        'Creating object: SS6AdminModule => SS6HTTPSConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "minTlsVersion" = ${MinTlsVersion}
            "maxTlsVersion" = ${MaxTlsVersion}
            "allowedCipherSuites" = ${AllowedCipherSuites}
        }

        return $PSO
    }
}
