#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
This is the IP address or full Host Name of the LDAP server

.PARAMETER Port
The port this service will bind to

.PARAMETER LdapProto
No description available.

.PARAMETER Username
Username of a user who has query permissions on this LDAP server

.PARAMETER Password
No description available.

.PARAMETER Domains
No description available.

.OUTPUTS

LDAPConfig<PSCustomObject>
#>

function New-SS6LDAPConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Port},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${LdapProto},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Username},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Password},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Domains}
    )

    Process {
        'Creating object: SS6AdminModule => SS6LDAPConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "port" = ${Port}
            "ldapProto" = ${LdapProto}
            "username" = ${Username}
            "password" = ${Password}
            "domains" = ${Domains}
        }

        return $PSO
    }
}
