#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

LDAP query type:   * `UPN` - will query only the user's UPN (User Principal Name)   * `sAMAcct` - will query only the user's sAMAccountName   * `UPN_sAMAcct` - will query the user's UPN (User Principal Name) and, if not found, it'll query the sAMAccountName after than   * `sAMAcct_UPN` - will query the user's sAMAccountName and, if not found, it'll query the UPN (User Principal Name) after than 

.OUTPUTS

LDAPQueryType<PSCustomObject>
#>

function New-SS6LDAPQueryType {
    [CmdletBinding()]
    Param (
    )

    Process {
        'Creating object: SS6AdminModule => SS6LDAPQueryType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
        }

        return $PSO
    }
}
