#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ColorOutput
No description available.
.OUTPUTS

LogToStdoutCfg<PSCustomObject>
#>

function Initialize-SS6LogToStdoutCfg {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ColorOutput}
    )

    Process {
        'Creating PSCustomObject: SS6AdminModule => SS6LogToStdoutCfg' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "colorOutput" = ${ColorOutput}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to LogToStdoutCfg<PSCustomObject>

.DESCRIPTION

Convert from JSON to LogToStdoutCfg<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

LogToStdoutCfg<PSCustomObject>
#>
function ConvertFrom-SS6JsonToLogToStdoutCfg {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: SS6AdminModule => SS6LogToStdoutCfg' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SS6LogToStdoutCfg
        $AllProperties = ("colorOutput")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "colorOutput"))) { #optional property not found
            $ColorOutput = $null
        } else {
            $ColorOutput = $JsonParameters.PSobject.Properties["colorOutput"].value
        }

        $PSO = [PSCustomObject]@{
            "colorOutput" = ${ColorOutput}
        }

        return $PSO
    }

}

