#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Version
No description available.

.PARAMETER Salt
No description available.

.PARAMETER Payload
No description available.

.PARAMETER MustChange
No description available.

.OUTPUTS

PasswordType<PSCustomObject>
#>

function New-SS6PasswordType {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Version},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Salt},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Payload},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${MustChange}
    )

    Process {
        'Creating object: SS6AdminModule => SS6PasswordType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "version" = ${Version}
            "salt" = ${Salt}
            "payload" = ${Payload}
            "mustChange" = ${MustChange}
        }

        return $PSO
    }
}
