#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Permissions
No description available.
.OUTPUTS

PermOverrider<PSCustomObject>
#>

function Initialize-SS6PermOverrider {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Permissions}
    )

    Process {
        'Creating PSCustomObject: SS6AdminModule => SS6PermOverrider' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Permissions -and $Permissions.length -lt 1) {
            throw "invalid value for 'Permissions', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "permissions" = ${Permissions}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PermOverrider<PSCustomObject>

.DESCRIPTION

Convert from JSON to PermOverrider<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PermOverrider<PSCustomObject>
#>
function ConvertFrom-SS6JsonToPermOverrider {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: SS6AdminModule => SS6PermOverrider' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SS6PermOverrider
        $AllProperties = ("permissions")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "permissions"))) { #optional property not found
            $Permissions = $null
        } else {
            $Permissions = $JsonParameters.PSobject.Properties["permissions"].value
        }

        $PSO = [PSCustomObject]@{
            "permissions" = ${Permissions}
        }

        return $PSO
    }

}

