#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER IpOrNetwork
No description available.

.PARAMETER Notes
No description available.

.OUTPUTS

SAListItem<PSCustomObject>
#>

function New-SS6SAListItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IpOrNetwork},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Notes}
    )

    Process {
        'Creating object: SS6AdminModule => SS6SAListItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "ipOrNetwork" = ${IpOrNetwork}
            "notes" = ${Notes}
        }

        return $PSO
    }
}
