#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
A unique ID for this SAML2.0 IdP, it will be auto-generated if empty

.PARAMETER SsoUrl
The SSO URL provided by the SAML2.0 IdP

.PARAMETER EntityIdUrl
The entity ID URL provided by the SAML2.0 IdP

.PARAMETER IdpCert
The X.509 certificate (public key only) of the SAML2.0 IdP

.PARAMETER AppName
The app name this instance of Syncplify.me Server! will present itself to the IdP with

.PARAMETER AppAcsUrl
The app (SMS) ACS URL that the IdP will call to consume the service

.PARAMETER AppEntityIdUrl
The local (SMS) entity ID URL that the IdP will call to bounce back

.PARAMETER AppCert
Our own (SMS) X.509 certificate to sign auth requests

.PARAMETER AppKey
The private key to our own (SMS) X.509 certificate to sign auth requests

.OUTPUTS

SAMLIdP<PSCustomObject>
#>

function New-SS6SAMLIdP {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SsoUrl},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EntityIdUrl},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IdpCert},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AppName},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AppAcsUrl},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AppEntityIdUrl},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AppCert},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AppKey}
    )

    Process {
        'Creating object: SS6AdminModule => SS6SAMLIdP' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "ssoUrl" = ${SsoUrl}
            "entityIdUrl" = ${EntityIdUrl}
            "idpCert" = ${IdpCert}
            "appName" = ${AppName}
            "appAcsUrl" = ${AppAcsUrl}
            "appEntityIdUrl" = ${AppEntityIdUrl}
            "appCert" = ${AppCert}
            "appKey" = ${AppKey}
        }

        return $PSO
    }
}
