#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Host
No description available.

.PARAMETER Port
No description available.

.PARAMETER Sender
No description available.

.PARAMETER User
No description available.

.PARAMETER Pass
No description available.

.PARAMETER TlsCliMode
No description available.

.OUTPUTS

SMTPConfig<PSCustomObject>
#>

function New-SS6SMTPConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Host},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Port},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Sender},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${User},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Pass},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TlsCliMode}
    )

    Process {
        'Creating object: SS6AdminModule => SS6SMTPConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "host" = ${Host}
            "port" = ${Port}
            "sender" = ${Sender}
            "user" = ${User}
            "pass" = ${Pass}
            "tlsCliMode" = ${TlsCliMode}
        }

        return $PSO
    }
}
