#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

SSH2 public key

.PARAMETER Id
No description available.

.PARAMETER Name
a free-text name for the public key

.PARAMETER Key
the key itself

.PARAMETER Fingerprint
No description available.

.PARAMETER Type
No description available.

.PARAMETER Comment
No description available.

.OUTPUTS

SSHPubKey<PSCustomObject>
#>

function New-SS6SSHPubKey {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Key},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Fingerprint},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Comment}
    )

    Process {
        'Creating object: SS6AdminModule => SS6SSHPubKey' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "key" = ${Key}
            "fingerprint" = ${Fingerprint}
            "type" = ${Type}
            "comment" = ${Comment}
        }

        return $PSO
    }
}
