#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

TLSCliModeType is the enumerable that represents the TLS client mode

.OUTPUTS

TLSCliModeType<PSCustomObject>
#>

function New-SS6TLSCliModeType {
    [CmdletBinding()]
    Param (
    )

    Process {
        'Creating object: SS6AdminModule => SS6TLSCliModeType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
        }

        return $PSO
    }
}
