#
# SMServer V6
# Syncplify Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Token
No description available.
.OUTPUTS

TokenObj<PSCustomObject>
#>

function Initialize-TokenObj {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Token}
    )

    Process {
        'Creating PSCustomObject: SS6AdminModule => TokenObj' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "token" = ${Token}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TokenObj<PSCustomObject>

.DESCRIPTION

Convert from JSON to TokenObj<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TokenObj<PSCustomObject>
#>
function ConvertFrom-JsonToTokenObj {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: SS6AdminModule => TokenObj' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TokenObj
        $AllProperties = ("token")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "token"))) { #optional property not found
            $Token = $null
        } else {
            $Token = $JsonParameters.PSobject.Properties["token"].value
        }

        $PSO = [PSCustomObject]@{
            "token" = ${Token}
        }

        return $PSO
    }

}

