#
# SMServer V6
# Syncplify.me Server! REST API
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Soft
No description available.

.PARAMETER Hard
No description available.

.OUTPUTS

VFSQuota<PSCustomObject>
#>

function New-SS6VFSQuota {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Soft},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Hard}
    )

    Process {
        'Creating object: SS6AdminModule => SS6VFSQuota' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $PSO = [PSCustomObject]@{
            "soft" = ${Soft}
            "hard" = ${Hard}
        }

        return $PSO
    }
}
